name: GitHub automated actions
on: push

jobs:
  hello_world:
    name: Printer workflow
    runs-on: ubuntu-latest

    steps:
      - name: Read repository content
        uses: actions/checkout@v4

      - name: Print message
        run: python hello_world_printer.py
